In [0]:
!pip install --upgrade grpcio
!pip install tensorflow==2.0

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

In [0]:
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_datasets as tfds

# Word Embeddings 

The embedding layer acts as a lookup table that maps the integer indices to vectors. When we create an embedding layer, the weights are randomly initialized and then adjusted via backpropogation during training.

The parameters to the Embedding Layer are input_dim, output_dim, and input size.

 *input_dim* is the size of the vocabulary.

*output_dim* is the size of the vector space in which the words are embedded, i.e. the dimension of the vector embeddings.

 *input_length* is the length of the input sequence.

In [0]:
embedding_layer = layers.Embedding(1000, 5)

Passing a sequence of integers to the embedding layer returns the floating point vector which is mapped to the integer sequence. 

In [6]:
result = embedding_layer(tf.constant([1, 4, 7, 9]))
print(dir(result))

# We print the 5-dim vectors for each of the integer in the sequence provided above.
print(result.numpy())


['OVERLOADABLE_OPERATORS', '_USE_EQUALITY', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__bool__', '__class__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__iter__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_add_consumer', '_as_node_def_input', '_as_tf_output', '_c_api_shape', '_copy', '_copy_nograd', '_co

We can pass a 2D tensor of integers to the Embedding layer, of shape **(number_of_samples, sequence_length)**. Each entry is a sequence of integers. The output is a 3D floating point tensor, which has shape **(number_of_samples, sequence_length, embedding_dim)**.

In [0]:
result = embedding_layer(tf.constant([[1,2,4], [2,3,4]]))

In [8]:
print(result.numpy())

[[[ 0.03986926 -0.03173438 -0.02799033  0.03823464  0.03856868]
  [-0.02281406  0.02966856  0.02286342  0.03767908  0.03811861]
  [ 0.00484568  0.0084567   0.00654433  0.01273901  0.03975483]]

 [[-0.02281406  0.02966856  0.02286342  0.03767908  0.03811861]
  [ 0.02198944  0.02700372  0.03230542  0.02984843 -0.00549867]
  [ 0.00484568  0.0084567   0.00654433  0.01273901  0.03975483]]]
