In [11]:
# !pip install --upgrade grpcio
!pip install tensorflow==2.0

In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.0.0
Eager execution is: True
Keras version: 2.2.4-tf


**Using Eager Execution**


In [2]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available(): 
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else: 
    print('Running on CPU')

Running on CPU


In [3]:
t0 = 24 # python variable
t1 = tf.Variable(42) # rank 0 tensor
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
print(t0, t1, t2)

24 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42> <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


In [8]:
# Casting a tensor to Numpy/Python variable
print(t2.numpy())

# Specifying an element of the tensor. Slice 1, row 0, column 2.
print(t2[1, 0, 2])

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
tf.Tensor(8.0, shape=(), dtype=float32)


In [9]:
# Size and datatype of a tensor
print("Size of t2: ", tf.size(input=t2).numpy())
print("Datatype of t2: ", t2.dtype)

Size of t2:  12
Datatype of t2:  <dtype: 'float32'>


***All of the operations that are available for tensors that form part of a computational graph are also available for eager execution variables.***

In [10]:
# Matrix transpose and matrix multiplication
u = tf.constant([[3,4,3]]) 
v = tf.constant([[1,2,1]])
tf.matmul(u, tf.transpose(a=v))

<tf.Tensor: id=62, shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [13]:
# Casting a tensor to another tensor datattyep
t1 = tf.constant(42)
print(t1)
print(tf.cast(t1, dtype=tf.float32))

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(42.0, shape=(), dtype=float32)


**Ragged Tensors:** A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.

In [15]:
# Ragged array of individual slices of length 4, 0, 3, 1, 2 respectively
ragged_tensor =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [17]:
# Creating ragged array using row_splits(), by providing a list of indices where the list is to be split
ragged_tensor = tf.RaggedTensor.from_row_splits(values=[5, 2, 6, 1, 4, 10, 7, 8, 6, 7], row_splits=[0, 4, 4, 7, 8, 10])
print(ragged_tensor)

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
